"feat: сделано задание 9‑го спринта"
Krivinsky/java-filmorate pull request #1
Opened 2022-09-17 21:29 UTC by Krivinsky

2022-09-17 21:34 UTC, Krivinsky commented
сделано задание 9‑го спринта)

2022-09-19 15:18 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(1);
почему всем проставляется один и тот же идентификатор. Фильмов ведь может быть много

2022-09-19 15:19 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Добавлен новый фильм в коллекцию");
В логах лучше отображать более подробную информацию. Этот лог не дает допольнительной информации для дебага приложения на проде

2022-09-19 15:21 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private int generateId() {
генератор идентификаротов есть, но он не используется

2022-09-19 15:26 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isEmpty()) {
Для чего эта проверка? Ведь в entity есть NotEmpty и можно еще поставить NotNull аннотации

2022-09-19 15:27 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String description;
Тоже можно использовать аннотации для проверки 
@Size(min = 1, max = 200)

2022-09-19 15:27 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    long duration;  //проверить формат
Длительность тоже можно проверить @Min(1)

2022-09-19 15:29 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895,12, 28))) {
Такие константы лучше выносить в глобальные, чтобы было одно место, где оно задается и было проще искать и править его

2022-09-19 15:35 UTC, EvgenyKoptubenko requested changes
Есть замечания. Поправь, пожалуйста.

2022-09-19 15:35 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film add(@RequestBody Film film) throws FilmExeption {
Если передать name null, то возвращается 500-я ошибка на сервере, но не понятно из-за чего она
В логе информация есть
ru.yandex.practicum.filmorate.exeption.FilmExeption: Ошибка в названии фильма
	at ru.yandex.practicum.filmorate.controller.FilmController.filmValidate(FilmController.java:53) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controller.FilmController.add(FilmController.java:24)

В ответе{
	"timestamp": "2022-09-19T15:34:15.334+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}

2022-09-20 20:08 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Переходи на следующий урок.

2022-09-25 09:40 UTC, merged